Repository exercism/red, pull requests merged in 2024-04, with the labels that each got.

#155 scrabble-score: sync
  exercises/practice/scrabble-score/.docs/instructions.md
  exercises/practice/scrabble-score/.docs/introduction.md
Labels: x:size/tiny

#157 Uncomment the solution file being tested
  exercises/practice/reverse-string/reverse-string-test.red
Labels: x:action/fix, x:rep/tiny

#160 Add allergies
  config.json
  exercises/practice/allergies/.docs/instructions.md
  exercises/practice/allergies/.meta/config.json
  exercises/practice/allergies/.meta/example.red
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/allergies/allergies-test.red
  exercises/practice/allergies/allergies.red
  exercises/practice/allergies/testlib.red
Labels: x:module/practice-exercise, x:rep/large
