Repository exercism/red, pull requests merged in 2024-02, with the labels that each got.

#130 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny

#135 Sort exercises by displayed difficulty and then name
  config.json
Labels: x:rep/tiny

#137 Format difference-of-squares config.json
  exercises/practice/difference-of-squares/.meta/config.json
Labels: x:rep/tiny

#138 Sync docs and metadata
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/roman-numerals/.docs/instructions.md
Labels: x:rep/tiny

#140 Update resistor-color-duo tests
  exercises/practice/resistor-color-duo/.meta/tests.toml
  exercises/practice/resistor-color-duo/resistor-color-duo-test.red
Labels: x:action/sync, x:rep/tiny

#139 Update reverse-string tests
  exercises/practice/reverse-string/.meta/tests.toml
  exercises/practice/reverse-string/reverse-string-test.red
Labels: x:action/sync, x:rep/tiny

#141 Update protein-translation tests
  exercises/practice/protein-translation/.meta/tests.toml
  exercises/practice/protein-translation/protein-translation-test.red
Labels: x:action/sync, x:rep/tiny

#142 Sync resistor-color-trio tests
  exercises/practice/resistor-color-trio/.meta/tests.toml
  exercises/practice/resistor-color-trio/resistor-color-trio-test.red
Labels: x:action/sync, x:rep/tiny

#143 Sync high-scores tests
  exercises/practice/high-scores/.meta/tests.toml
  exercises/practice/high-scores/high-scores-test.red
Labels: x:action/sync, x:rep/tiny

#144 Sync run-length-encoding
  exercises/practice/run-length-encoding/.meta/tests.toml
  exercises/practice/run-length-encoding/run-length-encoding-test.red
Labels: x:action/sync, x:rep/tiny

#146 roman-numerals: sync
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/config.json
Labels: x:size/tiny

#149 Add nucleotide-count
  config.json
  exercises/practice/nucleotide-count/.docs/instructions.md
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/nucleotide-count/.meta/example.red
  exercises/practice/nucleotide-count/.meta/tests.toml
  exercises/practice/nucleotide-count/nucleotide-count-test.red
  exercises/practice/nucleotide-count/nucleotide-count.red
  exercises/practice/nucleotide-count/testlib.red
Labels: x:module/practice-exercise, x:rep/medium

#150 Add acronym exercise
  config.json
  exercises/practice/acronym/.docs/instructions.md
  exercises/practice/acronym/.meta/config.json
  exercises/practice/acronym/.meta/example.red
  exercises/practice/acronym/.meta/tests.toml
  exercises/practice/acronym/acronym-test.red
  exercises/practice/acronym/acronym.red
  exercises/practice/acronym/testlib.red
Labels: x:module/practice-exercise, x:rep/medium
